enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

packageExtensions:
  '@storybook/addon-actions@*':
    dependencies:
      dequal: ^2.0.3
      polished: ^4.3.1
  '@storybook/addon-backgrounds@*':
    dependencies:
      memoizerific: ^1.11.3
      ts-dedent: ^2.2.0
  '@storybook/addon-controls@*':
    dependencies:
      '@storybook/global': ^5.0.0
      dequal: ^2.0.3
      ts-dedent: ^2.2.0
  '@storybook/addon-docs@*':
    dependencies:
      '@storybook/blocks': ^8.6.14
  '@storybook/addon-viewport@*':
    dependencies:
      memoizerific: ^1.11.3

yarnPath: .yarn/releases/yarn-4.18.0.cjs
